apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-jenkins
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: xxx
          image: nginx
