apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: xxx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80

