apiVersion: v1
kind: Namespace
metadata:
  name: my-space
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80

